"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False)
)

# Read .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['*'])


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party
    'rest_framework',
    
    # Local apps
    'apps.accounts',
    'apps.catalog',
    'apps.summaries',
    'apps.media',
    'apps.subscriptions',
    'apps.progress',
    'apps.home',
    'apps.notifications',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': env.db('DATABASE_URL', default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}")
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Celery Configuration
CELERY_BROKER_URL = env('REDIS_URL', default='redis://localhost:6379/1')

# AI Pipeline Settings
OPENAI_API_KEY = env('OPENAI_API_KEY', default='')
GEMINI_API_KEY = env('GEMINI_API_KEY', default='')
GEMINI_MODEL_NAME = env('GEMINI_MODEL_NAME', default='gemini-2.5-flash')
GEMINI_REQUEST_TIMEOUT_SECONDS = env.int('GEMINI_REQUEST_TIMEOUT_SECONDS', default=45)
PINECONE_API_KEY = env('PINECONE_API_KEY', default='')
PINECONE_ENVIRONMENT = env('PINECONE_ENVIRONMENT', default='')
PINECONE_INDEX_NAME = env('PINECONE_INDEX_NAME', default='blinkist-clone')

# AWS S3 Configuration (Optional - for Phase 2/3)
AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID', default='')
AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY', default='')
AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME', default='')
AWS_S3_REGION_NAME = env('AWS_S3_REGION_NAME', default='us-east-1')

if AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY:
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    STATICFILES_STORAGE = 'storages.backends.s3boto3.S3StaticStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Subscription / SSLCOMMERZ
SUBSCRIPTION_PRICE_BDT = env.float('SUBSCRIPTION_PRICE_BDT', default=149.0)
SSLCOMMERZ_STORE_ID = env('SSLCOMMERZ_STORE_ID', default='')
SSLCOMMERZ_STORE_PASSWORD = env('SSLCOMMERZ_STORE_PASSWORD', default='')
SSLCOMMERZ_SANDBOX = env.bool('SSLCOMMERZ_SANDBOX', default=True)
MOBILE_APP_RETURN_URL = env(
    'MOBILE_APP_RETURN_URL',
    default='blinkist:/payment-return',
)
CANCEL_AT_PERIOD_END = env.bool('CANCEL_AT_PERIOD_END', default=True)

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── Django Unfold Admin Configuration ─────────────────────────────────────────
from django.urls import reverse_lazy

UNFOLD = {
    "SITE_TITLE": "Blinkist Admin",
    "SITE_HEADER": "Blinkist Command Center",
    "SITE_SUBHEADER": "Microlearning & Audio Narration Platform",
    "SITE_URL": "/",
    "DASHBOARD_CALLBACK": "core.admin_dashboard.dashboard_callback",
    "COLORS": {
        "primary": {
            "50": "#E6FBF2",
            "100": "#CEF6E4",
            "200": "#9DEECA",
            "300": "#6CE5AF",
            "400": "#3BDD95",
            "500": "#00A86B",
            "600": "#00945E",
            "700": "#007A4E",
            "800": "#005F3D",
            "900": "#00472D",
            "950": "#002B1B",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Catalog & Content",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Books",
                        "icon": "menu_book",
                        "link": lambda request: reverse_lazy("admin:catalog_book_changelist"),
                    },
                    {
                        "title": "Authors",
                        "icon": "person_pin",
                        "link": lambda request: reverse_lazy("admin:catalog_author_changelist"),
                    },
                    {
                        "title": "Categories",
                        "icon": "category",
                        "link": lambda request: reverse_lazy("admin:catalog_category_changelist"),
                    },
                    {
                        "title": "Collections",
                        "icon": "collections_bookmark",
                        "link": lambda request: reverse_lazy("admin:catalog_collection_changelist"),
                    },
                    {
                        "title": "Daily Picks",
                        "icon": "auto_awesome",
                        "link": lambda request: reverse_lazy("admin:catalog_dailypick_changelist"),
                    },
                    {
                        "title": "Ingestion Pipeline",
                        "icon": "smart_toy",
                        "link": lambda request: reverse_lazy("admin:catalog_contentingestionjob_changelist"),
                    },
                ],
            },
            {
                "title": "Audio & Summaries",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Summary Sections",
                        "icon": "headphones",
                        "link": lambda request: reverse_lazy("admin:summaries_summarysection_changelist"),
                    },
                    {
                        "title": "User Audio Bookmarks",
                        "icon": "bookmark",
                        "link": lambda request: reverse_lazy("admin:summaries_useraudiobookmark_changelist"),
                    },
                    {
                        "title": "User Highlights & Notes",
                        "icon": "highlight",
                        "link": lambda request: reverse_lazy("admin:summaries_userhighlight_changelist"),
                    },
                    {
                        "title": "User Audio Queues",
                        "icon": "queue_music",
                        "link": lambda request: reverse_lazy("admin:catalog_useraudioqueueitem_changelist"),
                    },
                ],
            },
            {
                "title": "User Progress & Gamification",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Daily Habit Activities",
                        "icon": "local_fire_department",
                        "link": lambda request: reverse_lazy("admin:progress_userdailyactivity_changelist"),
                    },
                    {
                        "title": "Milestone Badges",
                        "icon": "military_tech",
                        "link": lambda request: reverse_lazy("admin:progress_userbadge_changelist"),
                    },
                    {
                        "title": "Book Reading Progress",
                        "icon": "auto_stories",
                        "link": lambda request: reverse_lazy("admin:progress_userbookprogress_changelist"),
                    },
                    {
                        "title": "Audio Listening Progress",
                        "icon": "graphic_eq",
                        "link": lambda request: reverse_lazy("admin:progress_useraudioprogress_changelist"),
                    },
                    {
                        "title": "Saved Libraries",
                        "icon": "bookmark_added",
                        "link": lambda request: reverse_lazy("admin:catalog_userlibraryitem_changelist"),
                    },
                ],
            },
            {
                "title": "Users & Access",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "User Accounts",
                        "icon": "group",
                        "link": lambda request: reverse_lazy("admin:accounts_user_changelist"),
                    },
                ],
            },
            {
                "title": "Communications & Analytics",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Push Notifications",
                        "icon": "notifications",
                        "link": lambda request: reverse_lazy("admin:notifications_notification_changelist"),
                    },
                    {
                        "title": "Notification Preferences",
                        "icon": "tune",
                        "link": lambda request: reverse_lazy("admin:notifications_notificationpreference_changelist"),
                    },
                    {
                        "title": "Search Query Trends",
                        "icon": "troubleshoot",
                        "link": lambda request: reverse_lazy("admin:catalog_searchquerylog_changelist"),
                    },
                ],
            },
        ],
    },
}
