# Generated by Django 6.0.3 on 2026-03-08 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummarySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Markdown or HTML content')),
                ('plain_text', models.TextField(blank=True, help_text='Plain text for search, indexing, and TTS fallback')),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('estimated_read_minutes', models.PositiveIntegerField(default=2)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='catalog.book')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('book', 'slug')},
            },
        ),
    ]
