# Generated by Django 6.0.3 on 2026-03-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summarysection',
            name='audio_url',
        ),
        migrations.AddField(
            model_name='summarysection',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='books/audio/'),
        ),
    ]
