# Generated by Django 4.2.29 on 2026-09-28 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_dailypick'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('summaries', '0002_remove_summarysection_audio_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_text', models.TextField()),
                ('note', models.TextField(blank=True, default='')),
                ('color', models.CharField(choices=[('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('pink', 'Pink')], default='yellow', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='catalog.book')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='summaries.summarysection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
