# Generated by Django 4.2.29 on 2026-10-08 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0011_searchquerylog'),
        ('summaries', '0004_useraudiobookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookFlashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_prompt', models.TextField(help_text='Core question or concept trigger')),
                ('back_answer', models.TextField(help_text='Clear explanation, principle, or actionable takeaway')),
                ('key_quote', models.TextField(blank=True, default='', help_text='Direct quote or memorable line from the book')),
                ('quiz_options', models.JSONField(blank=True, default=list, help_text="List of choices: [{'text': '...', 'is_correct': True, 'explanation': '...'}]")),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='catalog.book')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcards', to='summaries.summarysection')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserFlashcardReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('mastered', 'Mastered'), ('review_later', 'Review Later')], default='review_later', max_length=20)),
                ('times_reviewed', models.PositiveIntegerField(default=1)),
                ('last_reviewed_at', models.DateTimeField(auto_now=True)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to='summaries.bookflashcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_reviewed_at'],
                'unique_together': {('user', 'flashcard')},
            },
        ),
    ]
