# Generated by Django 6.0.3 on 2026-03-08 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('progress', '0001_initial'),
        ('summaries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookprogress',
            name='current_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='summaries.summarysection'),
        ),
        migrations.AddField(
            model_name='userbookprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersectionprogress',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='summaries.summarysection'),
        ),
        migrations.AddField(
            model_name='usersectionprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userbookprogress',
            unique_together={('user', 'book')},
        ),
        migrations.AlterUniqueTogether(
            name='usersectionprogress',
            unique_together={('user', 'section')},
        ),
    ]
