# Generated by Django 4.2.29 on 2026-10-06 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('progress', '0005_userdailyactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdailyactivity',
            name='audio_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdailyactivity',
            name='books_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdailyactivity',
            name='reading_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdailyactivity',
            name='sections_read',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_key', models.CharField(db_index=True, max_length=64)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'badge_key')},
            },
        ),
    ]
