# Generated by Django 6.0.3 on 2026-03-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_book_cover_image_url_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='full_text',
            field=models.TextField(blank=True, help_text='Complete book text for the Full Book reader'),
        ),
    ]
