# Generated by Django 6.0.3 on 2026-03-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_book_full_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='full_book_pdf',
            field=models.FileField(blank=True, help_text='Upload the full book as a PDF', null=True, upload_to='books/pdf/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='full_text',
            field=models.TextField(blank=True, help_text='Complete book text for the Full Book reader (fallback if no PDF)'),
        ),
    ]
