# Generated by Django 4.2.29 on 2026-09-30 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_dailypick'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='collections/banners/')),
                ('icon', models.CharField(blank=True, default='auto_stories', max_length=50)),
                ('color_hex', models.CharField(blank=True, default='#1E3A8A', max_length=7)),
                ('target_duration_days', models.PositiveIntegerField(default=7, help_text='e.g. 7 for a 7-day challenge')),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, help_text="e.g. 'Day 1: Build the mindset'", max_length=255)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='catalog.book')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.collection')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('collection', 'book')},
            },
        ),
    ]
