# Generated by Django 4.2.29 on 2026-10-02 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0009_book_rating_book_rating_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAudioQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_queued_by', to='catalog.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_queue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'added_at'],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
