# Generated by Django 4.2.29 on 2026-10-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_useraudioqueueitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=255, unique=True)),
                ('count', models.PositiveIntegerField(default=1)),
                ('last_searched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-count', '-last_searched_at'],
            },
        ),
    ]
