# Generated by Django 4.2.29 on 2026-09-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subscription_and_trial_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_active_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longest_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
