# Generated by Django 4.2.29 on 2026-09-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_dailypick'),
        ('accounts', '0003_user_current_streak_user_last_active_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_completed_onboarding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='interest_categories',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='user',
            name='interest_topics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_format',
            field=models.CharField(blank=True, default='both', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='reading_goal',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
